# Generated by Django 2.1.3 on 2019-07-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HermesEmailLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(max_length=1024, verbose_name='Recipients')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('ERROR', 'Error'), ('OK', 'OK')], default='NEW', max_length=16, verbose_name='Status')),
                ('response', models.CharField(blank=True, default='', max_length=256, verbose_name='Reponse')),
                ('retry_number', models.PositiveSmallIntegerField(default=0, verbose_name='Retry Number')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Email Logger',
                'verbose_name_plural': 'Emails Loggers',
            },
        ),
    ]
